### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by BinariGuy** [FriendlyNeighborhoodShane/MinMicroG_releases#11]
Hi dev, it would be possible to use MinMicroG for Android 12?
I dont know if this is the proper place but just wanted to know thanks.

**Comment by FriendlyNeighborhoodShane** [comment]
I don't know. Why don't you tell me 😄 

MinMicroG itself shouldn't have any problems with installation. You won't have some things, like contact sync adapters and AOSP keyboard swype libs (if you used standard), because they are specific to the Android version, and not yet available.

As for microG's own compatibility with Android 12, I know somebody who had managed to installed microG manually on an Android 12 build. You'll have to arrange for sigspoofing somehow, if you can't find a ROM that has it. How much of the functionality they tested and how much of it worked for them, I don't know.

Good luck!

**Comment by BinariGuy** [comment]
Hi its me again, i updated the ROM but google play didnt survive the update only MicroG but nothing else

**Comment by FriendlyNeighborhoodShane** [comment]
A log from that update session would've helped.

But I had fixed addon.d (the mechanism that makes minmicrog and other modifications survive ROM updates) for a couple of devices earlier. There isn't a stable release for it yet, but you can try your next ROM update with the latest CI build:
 https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI

Make sure to take the recovery logs, so I could take a look at them if it doesn't work.

Though you should always take care (that is, backups) when flashing any future CI builds. They're built and released automatically and are not tested by me to be working.

**Comment by BinariGuy** [comment]
Thanks, i have the orange fox log, i dont know if that can help.
Also for all the apps that disappeared what can i do?
Do a dirty flash or a clean installing the fresh ROM again?

**Comment by FriendlyNeighborhoodShane** [comment]
> [recovery_20211029_073524.log](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/7445978/recovery_20211029_073524.log)

Yup, you won't have this problem with the CI build. I'm planning to make a stable release on the next microg update.

> Also for all the apps that disappeared what can i do? Do a dirty flash or a clean installing the fresh ROM again? 

You'll have to flash it again. Don't worry, as you won't lose anything; not even permission. Permissions are only erased when you dirty flash minmicrog for the first time, as not doing so would cause problems.

**Comment by BinariGuy** [comment]
Sweet! so much thanks for this project man keep it up, dirty flashed the latest standar Cl build and now it appears that everything is just fine

**Comment by FriendlyNeighborhoodShane** [comment]
Neat!

**Comment by Omrigan** [comment]
Wasn't able to flush latest three builds from CI on top of crDroid android 12 :(
Only getting a bootloop

**Comment by FriendlyNeighborhoodShane** [comment]
Get the recovery logs from flashing and the logcat from the bootloop with the latest CI build. Which variant did you use?

**Comment by FriendlyNeighborhoodShane** [comment]
I just released a stable build:
https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/tag/2022.01.26

If you're still having trouble booting with that, we can reopen this issue.
