### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jason88fr** [FriendlyNeighborhoodShane/MinMicroG_releases#13]
Is the latest MinMicroG compatible with Android 12?

Device: [Xiaomi POCO F2 Pro aka Redmi K30Pro](https://www.gsmarena.com/xiaomi_poco_f2_pro-10220.php) (codename: lmi/LMI)

I'm on [CrDroid 8.1 (Android 12)](https://crdroid.net/lmi/8),  trying to get MinMicroG Standard variant to work.

I clean flashed as necessary to install the ROM, I was able to boot.

Upon returning to the recovery to flash (system install not Magisk) I got no errors on flashing the Standard variant but got stuck on the boot animation  upon rebooting to System after the flash.

**Comment by FriendlyNeighborhoodShane** [comment]
I don't know. Why don't you tell me 😄

MinMicroG itself shouldn't have any problems with installation. You won't have some things, like contact sync adapters and AOSP keyboard swype libs (if you used standard), because they are specific to the Android version, and not yet available.

As for microG's own compatibility with Android 12, I know somebody who had managed to installed microG manually on an Android 12 build. You'll have to arrange for sigspoofing somehow, if you can't find a ROM that has it. How much of the functionality they tested and how much of it worked for them, I don't know.

Good luck!

**Comment by feduss** [comment]
@jasonpremchand if you want to flash MinMicroG on A12, use the variant with fakestore...patched play store causes a bootloop because of a miss permission in allow list:

AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {[com.android](http://com.android/).vending (/system/priv-app/PatchPhonesky): [com.android](http://com.android/).permission.USE_INSTALLER_V2}

**Comment by jasonpremchand** [comment]
> I don't know. Why don't you tell me smile
> 
> MinMicroG itself shouldn't have any problems with installation. You won't have some things, like contact sync adapters and AOSP keyboard swype libs (if you used standard), because they are specific to the Android version, and not yet available.
> 
> As for microG's own compatibility with Android 12, I know somebody who had managed to installed microG manually on an Android 12 build. You'll have to arrange for sigspoofing somehow, if you can't find a ROM that has it. How much of the functionality they tested and how much of it worked for them, I don't know.
> 
> Good luck!

You're right, I should have phrased my question better and with more detail to help you and others seeing this.
I apologise, I'm not great at GitHub, yet!

**Comment by jasonpremchand** [comment]
&

> @jasonpremchand if you want to flash MinMicroG on A12, use the variant with fakestore...patched play store causes a bootloop because of a miss permission in allow list:
> 
> AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {[com.android](http://com.android/).vending (/system/priv-app/PatchPhonesky): [com.android](http://com.android/).permission.USE_INSTALLER_V2}

Would that be NoGoolag or Minimal variant?

I've reflashed the ROM and I'm using NikGapps because I read that for Google Photos backup to work, I would need to make a Titanium backup or Migrate backup of the Photos app and possible Contacts as well so as to facilitate syncing upon restoring the apps that have date made within a Gapps enabled environment.

That's part of the reason I stuck with the Standard variant as the person(s) advising the backup/restore fix for Photos indicated that they used Standard.

**Comment by FriendlyNeighborhoodShane** [comment]
> @jasonpremchand if you want to flash MinMicroG on A12, use the variant with fakestore...patched play store causes a bootloop because of a miss permission in allow list:

@feduss are you sure you're using the latest version? :)

https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/25ec2335b981407311953b6364505b1c22316243#diff-9120baf365bb6ce53756c9431a5f62055009bb6bd77f0c59d897b5e35f9f718e

**Comment by feduss** [comment]
@FriendlyNeighborhoodShane pretty sure, i was using v2.11.1 (02 february 2022) with magisk 24.1

**Comment by feduss** [comment]
> > @jasonpremchand if you want to flash MinMicroG on A12, use the variant with fakestore...patched play store causes a bootloop because of a miss permission in allow list:
> > AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {[com.android](http://com.android/).vending (/system/priv-app/PatchPhonesky): [com.android](http://com.android/).permission.USE_INSTALLER_V2}
> 
> Would that be NoGoolag or Minimal variant?
> 
> I've reflashed the ROM and I'm using NikGapps because I read that for Google Photos backup to work, I would need to make a Titanium backup or Migrate backup of the Photos app and possible Contacts as well so as to facilitate syncing upon restoring the apps that have date made within a Gapps enabled environment.
> 
> That's part of the reason I stuck with the Standard variant as the person(s) advising the backup/restore fix for Photos indicated that they used Standard.

yes, i'm using NoGoolag :)

**Comment by FriendlyNeighborhoodShane** [comment]
> @FriendlyNeighborhoodShane pretty sure, i was using v2.11.1 (02 february 2022) with magisk 24.1 :D

That is very strange. I added that to the allowlist over two months ago, and all releases/CI builds since have it.

If you still wish to get playstore working we can look into it. Just open a new issue for it with the full logcat and the installation logs.

**Comment by jason88fr** [comment]
> Ah I hadn't even noticed that the opening post was updated.
> 
> @jason88fr can you get a logcat of the bootloop? Also probably get the recovery logs just after flashing minmicrog, to make sure nothing is going wrong during installation (you can just flash the minmicrog zip again to get them).

Uh oh, I can't, I flashed CrDroid 8.1 then nikgapps to make a few apps in a gapps environment to restore them later to enable backup/sync. Eg Google photos

**Comment by FriendlyNeighborhoodShane** [comment]
> Uh oh, I can't, I flashed CrDroid 8.1 then nikgapps to make a few apps in a gapps environment to restore them later to enable backup/sync. Eg Google photos

That's okay. Feel free to do so at your convenience, if you still want to look into it.

**Comment by BinariGuy** [comment]
Havent tried an A12 enviroment, but for now im using AICP Lavender A11, i have magisk v23 with MinMicroG v2.11.1 play store patched, what would happen if i install the Magisk v24.1 along with the MinMicroG Standar? and for some reason i have the MinMicroG installed on Magisk

**Comment by BinariGuy** [comment]
Just tried to uninstall the MinMicroG since while trying to replace the playstore i messed up with something, i didnt get a bootloop luckly but i have the same apps installed do i need to uninstall them manually or theres something wrong?

**Comment by FriendlyNeighborhoodShane** [comment]
> Just tried to uninstall the MinMicroG because i was trying to replace the playstore and i messed up with something, i didnt get a bootloop luckly but i have the same apps installed do i need to uninstall them manually or theres something wrong? Or i can install the zip again without clean flash the ROM again

Yes, you can just flash another zip (with the older playstore) to replace the version with the crashing patched playstore.

**Comment by BinariGuy** [comment]
Thanks but i did a clean flash again, im not that smart to do that, i mean replace the outdated with the updated play store

**Comment by FriendlyNeighborhoodShane** [comment]
> Thanks but i did a clean flash again, im not that smart to do that, i mean replace the outdated with the updated play store

@BinariGuy I'm not really sure I got what you meant.

In general you can switch between different minmicrog versions/variants by just flashing a different zip, without needing to clean flash. (Only the first flash is recommended to be a clean flash.)

So if you meant that you want to try out the experimental patched playstore, you can simply flash the CI zip that has it. If you want to switch back to the old nanolx playstore, you can simply flash the latest stable release zip.

**Comment by BinariGuy** [comment]
I wasnt comfortable so i did a clean flash for some reasons, but yeah i didnt know i could do that

**Comment by FriendlyNeighborhoodShane** [comment]
@jason88fr the bootloop should be fixed with https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.02.20

Feel free to reopen if that still happens.
