### ISSUE TITLE
PatchPhonesky causes bootloop on Android 12

### ISSUE THREAD

**Issue by feduss** [FriendlyNeighborhoodShane/MinMicroG_releases#14]
I have tried to flash MinMicroG with patched playstore both using magisk and twrp, but i always got a bootloop with the following errors (i don't have the full logcat, sorry...and i can't get it because this device is my daily):

`02-08 12:53:03.311  3442  3442 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.vending (/system/priv-app/PatchPhonesky): com.android.permission.USE_INSTALLER_V2}
02-08 12:53:03.311  3442  3442 E System  :   at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:4577)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.server.pm.permission.PermissionManagerService.access$800(PermissionManagerService.java:191)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.onSystemReady(PermissionManagerService.java:5051)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:24681)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.server.SystemServer.startOtherServices(SystemServer.java:2621)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.server.SystemServer.run(SystemServer.java:881)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.server.SystemServer.main(SystemServer.java:612)
02-08 12:53:03.311  3442  3442 E System  :   at java.lang.reflect.Method.invoke(Native Method)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-08 12:53:03.311  3442  3442 E System  :   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
02-08 12:53:03.311  3442  3442 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 139ms
02-08 12:53:03.311  3442  3442 E Zygote  : System zygote died with fatal exception
02-08 12:53:03.311  3442  3442 E Zygote  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.vending (/system/priv-app/PatchPhonesky): com.android.permission.USE_INSTALLER_V2}
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:4577)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.server.pm.permission.PermissionManagerService.access$800(PermissionManagerService.java:191)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.onSystemReady(PermissionManagerService.java:5051)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:24681)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.server.SystemServer.startOtherServices(SystemServer.java:2621)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.server.SystemServer.run(SystemServer.java:881)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.server.SystemServer.main(SystemServer.java:612)
02-08 12:53:03.311  3442  3442 E Zygote  :   at java.lang.reflect.Method.invoke(Native Method)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-08 12:53:03.311  3442  3442 E Zygote  :   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
02-08 12:53:03.311  3442  3442 D AndroidRuntime: Shutting down VM
02-08 12:53:03.311  3442  3442 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
02-08 12:53:03.311  3442  3442 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.vending (/system/priv-app/PatchPhonesky): com.android.permission.USE_INSTALLER_V2}
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:4577)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.server.pm.permission.PermissionManagerService.access$800(PermissionManagerService.java:191)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.onSystemReady(PermissionManagerService.java:5051)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:24681)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.server.SystemServer.startOtherServices(SystemServer.java:2621)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.server.SystemServer.run(SystemServer.java:881)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.server.SystemServer.main(SystemServer.java:612)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-08 12:53:03.311  3442  3442 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)`

I didn't have any problems with the zip containing FakeStore.

Device: Sony xperia xz1
OS: Android 12 (LineageOS 19.0)
Magisk: 24.1 with zygote enabled
Twrp: 3.6.0_9-0

PS: thanks for your great work btw :D

**Comment by FriendlyNeighborhoodShane** [comment]
I see.

At first glance, this just seems impossible to me. It's possible that the allowlist file was not installed because of some weird error, but then why would it only complain about this one privileged permission and not the dozen others that playstore demands? It's hard to speculate without more information.

Anyway, do tell if at some point in the future you feel like experimenting again.

**Comment by feduss** [comment]
> We'll need a logcat of the bootloop, and a recovery log of minmicrog's installation (you can just flash the zip again to get it).

Today i'll get you these log...it's the same magisk log, instead of recovery one? If i flash the zip from TWRP, magisk doesn't see it as module

**Comment by FriendlyNeighborhoodShane** [comment]
@feduss 

> it's the same magisk log, instead of recovery one?

Yep. You can get the magisk manager log, if you're using that to install minmicrog.

> If i flash the zip from TWRP, magisk doesn't see it as module

Make sure you've decrypted your data partition before flashing it (because magisk modules are stored in your data, minmicrog can't install itself as a module if data is left encrypted).

Also if you're clean flashing your ROM, on some devices you may need to boot once after installing magisk to let it set itself up properly, and then come back to your recovery to flash modules.

It is recommended to flash minmicrog from recovery rather than from magisk manager, otherwise you may face problems with permissions to some system apps.

**Comment by feduss** [comment]
> Make sure you've decrypted your data partition before flashing it (because magisk modules are stored in your data, minmicrog can't install itself as a module if data is left encrypted).

ok, now it's clear...my twrp is not updated to support android 12 yet, and it can't decrypt /data...thanks for the clarification! I will provide you both logs asap...thanks for the clarification!

**Comment by MarcoDjallo** [comment]
I have the same problem with TWRP not updated also on my phone.
By the way, I installed patched play store using MicroG Installer Revived and it worked, no bootloop, purchases and IAP working.

I think it works differently: it asks you to put the apk of the play store version you want to install inside /data/adb/, then flash the zip via magisk; it will check that folder and if it finds a file named Phonesky.apk it will install it. I don't know if that could be useful.

**Comment by feduss** [comment]
@FriendlyNeighborhoodShane you can find the request logs below:

magisk:
[magisk_install_log_2022-02-11T18_18_34.log](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/8050624/magisk_install_log_2022-02-11T18_18_34.log)

bootloop (is too big for github):
https://mega.nz/file/EV11DaZB#6UPHg8PXPeuAGfU9cR9PWYrFBJPx8LDwmTTSfwx_wNg

it's weird, but i can't find PathPhonesky error this time, and i still have microg after removing the magisk module (when you enter in safe mode, magisk disable all modules)

**Comment by FriendlyNeighborhoodShane** [comment]
> i still have microg after removing the magisk module (when you enter in safe mode, magisk disable all modules)

Yeah, the init script installs microg as a user app update to fix some permissions. You should now be able to simply uninstall it like any other user app in this state.

> bootloop (is too big for github): https://mega.nz/file/EV11DaZB#6UPHg8PXPeuAGfU9cR9PWYrFBJPx8LDwmTTSfwx_wNg

Interesting.

No, I actually want to bang my head on the table right now. I searched for it and found the missing priv-perm error, e.g. on line 10579.

If you are able to boot in safe mode, can you open a file manager and confirm that the 4th-last line in `/data/adb/modules/MinMicroG//system/etc/permissions/com.android.vending.xml` is:
```
        <permission name="android.permission.USE_INSTALLER_V2" />
```

If it's there (and I'm pretty sure it is), I don't understand why Android is throwing that error.

Off the top of my head, maybe Magisk is mounting the permission files too late for Android to read them. But why is it only complaining about this one permission, and not others?

As an experiment, could you try installing MinMicroG as system, and see if you still get a bootloop?

**Comment by feduss** [comment]
> If you are able to boot in safe mode, can you open a file manager and confirm that the 4th-last line in `/data/adb/modules/MinMicroG//system/etc/permissions/com.android.vending.xml` is:
> 
> ```
>         <permission name="android.permission.USE_INSTALLER_V2" />
> ```
> 
> If it's there (and I'm pretty sure it is), I don't understand why Android is throwing that error.
> 
```
G8341:/data/adb/modules/MinMicroG/system # cd permissions
/system/bin/sh: cd: /data/adb/modules/MinMicroG/system/permissions: No such file or directory
G8341:/data/adb/modules/MinMicroG/system # ls
app  bin  etc  framework  priv-app
```
:O...there's no permissions folder

> As an experiment, could you try installing MinMicroG as system, and see if you still get a bootloop?

How?


Btw i'm still in safe mode, if you need it...we can chat on telegram if you want, to talk faster

**Comment by FriendlyNeighborhoodShane** [comment]
> :O...there's no permissions folder

There's an `/etc/` directory in between you missed :)

> How?

Uninstall the module, and just flash MinMicroG from your recovery. Since your data is encrypted, it will automatically install itself to system.

> Btw i'm still in safe mode, if you need it...we can chat on telegram if you want, to talk faster

Sure, I have a link to an unofficial microG Telegram group in the MinMicroG readme. Or my direct handle on telegram is `@ShaneTheAwesome`

**Comment by FriendlyNeighborhoodShane** [comment]
https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/53ff515063fb07c94e14bd570f90d1634e9a6578 seems to fix this particular bootloop for some (and it's really ridiculous).

I've made a CI build:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.02.20

Do try and tell if that fixes it for you.

**Comment by feduss** [comment]
Fixed by --> https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/53ff515063fb07c94e14bd570f90d1634e9a6578 

:D
