### ISSUE TITLE
[upstream Android bug] Intent Verification Filter keeps stopping

### ISSUE THREAD

**Issue by drishal** [FriendlyNeighborhoodShane/MinMicroG_releases#15]
as the title says, I occasionally keep getting the following error: Intent Verification Filter keeps stopping 

Zip flashed in recovery: [this one
](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/download/2022.02.02/MinMicroG-Standard-2.11.1-20220202153527.zip)

Logs: 
[Log_2022-02-19_21-42-28.txt](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/8102569/Log_2022-02-19_21-42-28.txt)

Device: Mi 11x (alioth)
Rom: ArrowOS 12 vanilla 

can anyone please help me in what is going on and solve the issue?

**Comment by FriendlyNeighborhoodShane** [comment]
a) That filtered logcat does not include any useful information about the crash itself, not even the stacktrace.

b) Have you determined in some way that this crash is related to minmicrog (or microg or any of the other included apps), and not a problem with your ROM or some other apps? For instance, does the crash stop happening after you uninstall minmicrog?

minmicrog does not touch any part of the system related to the intent verification service component (beyond what intent filters the apps themselves add, which are the same for everybody who uses those apps, and if were problematic would be faced by everybody), so I am skeptical that this is a minmicrog problem.

**Comment by drishal** [comment]
I had the sudden idea to clear data of Intent Verification Filter and there have been no issues till now atleast 
I am still not sure of what happened that could perhaps have cause IVF data to crash the service...closing this issue for now (might reopen if it comes back)

**Comment by drishal** [comment]
So I switched to crdroid and flashed minmicrog again there
This time there was a button for crash logs so i grabbed this 
`time: 1648326977908
msg: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
stacktrace: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
	at androidx.work.Data.toByteArrayInternal(Data.java:417)
	at androidx.work.Data$Builder.build(Data.java:846)
	at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227)
	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:1013)
`

**Comment by drishal** [comment]
So I switched to crdroid and flashed minmicrog again there
This time there was a button for crash logs so i grabbed this 
`time: 1648326977908
msg: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
stacktrace: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
	at androidx.work.Data.toByteArrayInternal(Data.java:417)
	at androidx.work.Data$Builder.build(Data.java:846)
	at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227)
	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:1013)
`

**Comment by FriendlyNeighborhoodShane** [comment]
>`time: 1648326977908 msg: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized stacktrace: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized at androidx.work.Data.toByteArrayInternal(Data.java:417) at androidx.work.Data$Builder.build(Data.java:846) at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44) at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227) at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137) at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:1013) `

This tiny snippet also doesn't contain any details, not even the packagename.

Wanting to obfuscate or filter out your system logs for privacy reasons is an understandable desire (secrets leaking through them are, of course, not unheard of), but it _really_ doesn't make it easy for people trying to help, unless you actually know exactly which parts are relevant and which are not.

Anyway, if you really do want to diagnose whatever issue you're having on your own:
if that stacktrace is for package `com.google.android.gms`, that looks like a code problem, and you should open an issue at https://github.com/microg/gmscore. And they *will* want the full logcat.

**Comment by drishal** [comment]
Hmm interestingly i flash just the minimal minmicrog on a clean crdroid 
No more issues for now 
I wonder if old version of play Store or something caused issues in the standard edition 🤔🤔

**Comment by FriendlyNeighborhoodShane** [comment]
Alright, cool.

**Comment by k2helix** [comment]
I'm using Minimal minmicrog and I'm getting this same error. LineageOS 19.1

**Comment by FriendlyNeighborhoodShane** [comment]
> I'm using Minimal minmicrog and I'm getting this same error. LineageOS 19.1

You haven't provided any logcats or any other meaningful context. How did you flash minmicrog? Clean flash or dirty flash?

Also see the comments above about there being very little interaction between minmicrog and IVS.

**Comment by k2helix** [comment]
> > I'm using Minimal minmicrog and I'm getting this same error. LineageOS 19.1
> 
> You haven't provided any logcats or any other meaningful context. How did you flash minmicrog? Clean flash or dirty flash?
> 
> Also see the comments above about there being very little interaction between minmicrog and IVS.

Sorry, I am/was not able to get a logcat as the error is quite random and I cannot seem to reproduce it whenever I want.

It was a clean flash, and we think it is caused by minmicrog/microg itself, as we found that everyone that got this issue flashed microg. It was also discussed in this [reddit post](https://www.reddit.com/r/MicroG/comments/ukb4x6/lineage_191_issue/)

I'm not certain if it is a minmicrog or a microg issue, so sorry if it is the second.

**Comment by ConcurrentCrab** [comment]
> and we think it is caused by minmicrog/microg itself, as we found that everyone that got this issue flashed microg. It was also discussed in this [reddit post](https://www.reddit.com/r/MicroG/comments/ukb4x6/lineage_191_issue/)

Interesting. One person there mentions even having it on LOS4uG, though I think it'd be better to not assume anything from anecdotal evidence.

There seems to be no issue about this on microg's tracker yet: https://github.com/microg/GmsCore/issues?q=%22intent+verification+filter%22

In either case, there's not much of a lead here for me (or the microG devs, for that matter) to follow, not without atleast a log of the crash.

**Comment by k2helix** [comment]
I understand, thanks for your answer.

I will attemp to obtain a logcat and if I am able to do it I will let you know.

**Comment by k2helix** [comment]
> In either case, there's not much of a lead here for me (or the microG devs, for that matter) to follow, not without atleast a log of the crash.

I was able to catch the error with a Fdroid app called Scoop. In previous days I noticed it happened when installing/updating apps. In my case I use Aurora Store with root installer.

The error occurred when installing an update to the GitHub app on Aurora, GitHub was updated successfully but here's what Scoop caught

```
FATAL EXCEPTION: pool-3-thread-4
Process: com.android.statementservice, PID: 17190
java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
	at androidx.work.Data.toByteArrayInternal(Data.java:417)
	at androidx.work.Data$Builder.build(Data.java:846)
	at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227)
	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by FriendlyNeighborhoodShane** [comment]
> I was able to catch the error with a Fdroid app called Scoop. In previous days I noticed it happened sometimes when installing/updating apps. In my case I use Aurora Store with root installer.
> 
> The error occurred when installing an update to the GitHub app on Aurora, GitHub was updated successfully but here's what Scoop caught

I see. But it's not at all obvious to me why microG would be involved during installation of apps, much less why it would crash a system service.

> Knowing this, I think I can get a full logcat, but what arguments should I pass to the command so I only get what we want?

The logcat command only has very naive functionality for filtering its output. You can just dump the entire log.

As for the part you'll have to post to online strangers, search for the crash in it and select a portion of about a minute or so around the crash, as knowing what else was happening in the system around that time could be useful.

**Comment by guillaume-smo** [comment]
Same problem here after updating from los18 + microg to los19 microg on samsung s10e, i will follow this issue to see if any progress is made on lineage ans/or microg sides, thanks.

**Comment by FriendlyNeighborhoodShane** [comment]
Calyx does seem to have an issue on it for quite a while:
https://gitlab.com/CalyxOS/calyxos/-/issues/831

Apparently, to quote Uldiniad from there:
> The cause is known. The fix is non-trivial

Their temporary solution to this (that is being upstreamed) seems to be just silencing all crashes from the Intent Verification Service.

Guess I'll keep this open for reference, until it's addressed for everybody properly.

**Comment by ale5000-git** [comment]
The real fix is now on LineageOS: https://github.com/LineageOS/android_frameworks_base/commit/fce1b15db00aae4447456359ac1c16bf773bbb26

**Comment by k2helix** [comment]
So after using the latest build for two days I've not encountered this bug anymore. If it happens anytime I'll let you know

**Comment by FriendlyNeighborhoodShane** [comment]
Alright, cool.
