### ISSUE TITLE
Aurora store in Nogoolag 2.11.1 is outdated not working

### ISSUE THREAD

**Issue by BlessedModding** [FriendlyNeighborhoodShane/MinMicroG_releases#16]
Aurora store provided in microG package 2.11.1 Nogoolag is version 4.0.7 and is not working it will not connect, fix is after installing the .zip, update to the latest aurora store at the gitlab release page (download the latest aurora store apk and update it on device), I would like to thank the devs of minMicroG and the microG devs thank you for your time God bless.

**Comment by FriendlyNeighborhoodShane** [comment]
Yes, Aurora changed its anonymous token servers, so anonymous logins won't work on that older version.

There's a CI build with updated aurora (and a couple of other things like a12 bootloop fixes) here:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases

I'll make a stable release soon, but I'm trying to get an updated patched playstore to work before that.
