### ISSUE TITLE
Can't give playstore sigspoof permission

### ISSUE THREAD

**Issue by A7pr8** [FriendlyNeighborhoodShane/MinMicroG_releases#17]
I had this problem on both los 18 + los 19
Nothing happens when I click on playstore in self-check in microg
Even though when I replace playstore with fakestore I can give it sigspoof permission
I tried using non-sigspoof rom with lsposed
And a sigspoof rom and both has the same result

**Comment by A7pr8** [comment]
Bro that is still not working

**Comment by FriendlyNeighborhoodShane** [comment]
How is it not working? What's the output of npem? How did you add sigspoof to LOS?

If you're using xposed and fakegapps, I hear the latest release of fakegapps is broken on A12. You need to use the 2nd last release.

**Comment by A7pr8** [comment]
Bro I am a sigspoofed rom + I tried fakegapps on los 18 and got the same error 
I tried pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE and npem and it didn't work

**Comment by FriendlyNeighborhoodShane** [comment]
You're not really giving me a lot of useful details here.

> I tried fakegapps on los 18 and got the same error

I don't know much about troubleshooting fakegapps. You'll have to ask the fakegapps developer for that.

> I tried pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE and npem and it didn't work on both sigspoofed rom and fakegapps

What was the output for both of those commands?

**Comment by A7pr8** [comment]
The output was nothing (in pm command)
Bro if u need any logs then tell me how to do it and I will send them immediately

I heard that patched playstore doesn't work with los 19 but I am not sure about this

**Comment by A7pr8** [comment]
Yeah there was nothing when I use pm neither on los 18 nor fakegapps nor los 19

I am not sre about special screen but I heare people say an12 won't work with patched playstore or they get booloop or whatever

**Comment by FriendlyNeighborhoodShane** [comment]
The bootloop was fixed some time ago with a CI build:
https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/issues/14

**Comment by A7pr8** [comment]
Thank u so much it is working fine now

**Comment by FriendlyNeighborhoodShane** [comment]
How did you get it working?

**Comment by A7pr8** [comment]
The new version worked (I was able to give patched playstore sigspoof permission) and now safety net work too

Small question for microg build (rom prebuilt with microg) how can we apply this patch or update on it so it won't bootloop?
