### ISSUE TITLE
[Question] Youtube Vanced needs another microG variant?

### ISSUE THREAD

**Issue by BinariGuy** [FriendlyNeighborhoodShane/MinMicroG_releases#18]
Hi again friendlyneighborhoodShane, and as the title says, do i need to install another version of microG for youtube Vanced?

**Comment by FriendlyNeighborhoodShane** [comment]
Yes, I believe so.

But you should really be asking the vanced people this, as I don't use it.

**Comment by BinariGuy** [comment]
No problem, now i going to stop bothering you have a nice day
