### ISSUE TITLE
GmsCore (and some others) not getting installed?

### ISSUE THREAD

**Issue by kerostampcrab** [FriendlyNeighborhoodShane/MinMicroG_releases#19]
Hey!

I am running OxygenOS 12 on OnePlus 9 Pro (L2123)
I am not good at this kind of stuff, so sorry if this is just me being dumb with something or if I missed something.

I got this to work once, but then I had to factory reset my device because it started bootlooping (I don't know the cause).

So now when I flash this on Magisk, and reboot, I don't seem to find GmsCore. This didn't previously come up on my home screen and so because I use LSPosed with the FakeGapps module (for signature spoofing), I usually launched it from there. It doesn't show up now tho.

I see MicroG Services Framework, Apple and Mozilla UnifiedNLP.

I tried with the standard package, minimal package and also updately minimal package.

I see folders for the apps MicroG and all the stuff that should be installed in /system/app and /priv-app (not sure if this means anything)

**Comment by FriendlyNeighborhoodShane** [comment]
OxygenOS? You _have_ debloated GApps from it, haven't you? What did you use?

If you can see the apks in `/system`, then maybe they got installed fine, but are not being loaded for whatever reason. The installation logs are still required to say anything for sure.

And you're not supposed to flash MinMicroG from the magisk manager. It should always be flashed from recovery. It will automatically install itself as a magisk module as long as magisk is installed and your `/data` is not encrypted.

Also, either of the repos are fine for creating issues. The 2-repos thing has definitely created some confusing situations for people about matters like these, will probably need to sort it out somehow in the future.

**Comment by kerostampcrab** [comment]
I used Universal Android Debloater (I think it uses ADB?)

Where are these installation logs?

I'll try that later.

I did kind of think that it's probably fine to have the issue there but I wanted to be sure

**Comment by kerostampcrab** [comment]
https://forum.xda-developers.com/t/recovery-11-official-teamwin-recovery-project.4294289/post-86749901

I might have to wait. Or maybe there's something else I can do?

**Comment by FriendlyNeighborhoodShane** [comment]
> I used Universal Android Debloater (I think it uses ADB?)

Yeah, that's the issue. That debloater doesn't actually remove those apps, only disables them. Which is why it they're conflicting with microG.

I don't recommend using stock roms at all, but if you are using it, try using one of the debloaters suggested in INSTALL.md.

> Where are these installation logs?

The recovery log can be saved using an option somewhere (I believe under 'Advanced' in TWRP)

**Comment by kerostampcrab** [comment]
The debloater will disable if you choose the option in it's settings, otherwise it'll uninstall them. 

I want to use OxygenOS because I like it.

I will try one of the debloaters in your little INSTALL.md

**Comment by kerostampcrab** [comment]
Imma close this for now

**Comment by FriendlyNeighborhoodShane** [comment]
> The debloater will disable if you choose the option in it's settings, otherwise it'll uninstall them.

It's not actually removing those applications from your device's system partitions, only pseudo-"uninstalling" them using an adb command, and only for a single user. And as that tool's documentation probably mentions (and if it doesn't, it should), you can bring any of those apps back with a single adb command, because it's just a trick that in the end is not that different from just disabling them.

**Comment by kerostampcrab** [comment]
Yup. I did think ADB seems a bit too easy for debloating for reasons like this.

So I installed De-Bloater from F-Droid, and uninstalled Gapps. Now after installing MinMicroG all seems to be working!

Thanks for the help
