### ISSUE TITLE
Migration back to lineage.microg.org builds?

### ISSUE THREAD

**Issue by michaelschefczyk** [FriendlyNeighborhoodShane/MinMicroG_releases#2]
Dear FriendlyNeighborhoodShane,

Thank you very much for publishing MinMicroG_releases! You wrote "... until Marvin revives microG to its former glory." It does seem that lineae.microg.org is indeed coming back to its former glory now.

As there were many months of uncertainty and no updates, I reinstalled some of my family phones with pure lineageos. As finding GPS locations in pure lineageos is often slow, I added your .zip.

Now the question is in line with your statement: How to revert to the builds at lineageos.microg.org? Can one avoid a complete reinstall? Is it possible to use the microg migration tool and dirty flash Marvin's build?

Regards,

Michael

**Comment by FriendlyNeighborhoodShane** [comment]
I'm not sure of the details but I don't think you can switch freely between lineage and lineage4µG without a data wipe. They're both signed with different release keys.

You can use app data backup apps like OAndBackupX (from FDroid) to make the shift easier though.
