### ISSUE TITLE
IchnaeaNlpBackend - update to 1.5.0

### ISSUE THREAD

**Issue by biopsin** [FriendlyNeighborhoodShane/MinMicroG_releases#21]
Hey,

noticed while back a new [release](https://github.com/microg/IchnaeaNlpBackend/releases)

**Comment by FriendlyNeighborhoodShane** [comment]
Yep, there's a nightly build with this change: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.05.13
(Github broke my CI builds somehow (and didn't even mail me about it SMH) so this wasn't released on the same night as the update, only when I noticed and fixed the problem).

I do intent to release a stable build with this plus other important updates (including A12 support), but I just can't carve out the time to hit another goal I wanted to before that: patching an up-to-date playstore.
