### ISSUE TITLE
Play Store always showing "Offline" despite having a proper internet connection.

### ISSUE THREAD

**Issue by alou-S** [FriendlyNeighborhoodShane/MinMicroG_releases#23]
Well the issue is just as it is mentioned in the title. No idea what is really causing it.

Over my various reinstalls of MicroG this happened thrice and somehow in one of the installs the error didn't occur. 

This issues has also been observed in : https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/issues/22#issuecomment-1146782012 

I have no idea what triggers this. It cannot be since google servers are blocked since I tried it both via Mobile Data and Wifi.

**Comment by FriendlyNeighborhoodShane** [comment]
Make sure that the internet permission (if your ROM allows you to toggle that) isn't denied to playstore. Also make sure you don't have any device-level adblocking like adaway.

Is your microG self-check all okay?

**Comment by alou-S** [comment]
microG self-check is alright. Internet permission isn't denied and device level adblocking doesn't exist.

Besides that i magically solved the issue by first using microg revived installer which doesn't have the internet issue, logging in, and then flashing your microg installer after removing revived.

**Comment by crestcere** [comment]
I got same error and manage to install with microg revived module. I think the installation script needs to improve as revived module did. Self-check was working great and internet permission is not blocked.

**Comment by FriendlyNeighborhoodShane** [comment]
Should be fixed with the latest CI release:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.10.30

Run the command `npem` manually from a root or ADB shell if not installed as a magisk module.

**Comment by alou-S** [comment]
@FriendlyNeighborhoodShane Luckily I had to do a clean flash to LOS 20 today and hence reinstalling microG. And this released has branched out an entirely new issue. Now I can't even Sign In on microG since when clicking sign in it gives the error : 
"Sorry... You don't have a network connection. This could be a temporary problem or your Android device may not be provisioned for data services. Try again when connected to a mobile network, or connect to a Wi-Fi Nework."

Also another thing I have noticed is Test SafetyNet fails with "Failed : Unable to resolve host www.googleapis.com" so I guess its some sort of DNS resolution issue.

And no I don't think its due to LOS 20 since microG revived still works fine.

**Comment by FriendlyNeighborhoodShane** [comment]
> @FriendlyNeighborhoodShane Luckily I had to do a clean flash to LOS 20 today and hence reinstalling microG. And this released has branched out an entirely new issue. Now I can't even Sign In on microG since when clicking sign in it gives the error : "Sorry... You don't have a network connection. This could be a temporary problem or your Android device may not be provisioned for data services. Try again when connected to a mobile network, or connect to a Wi-Fi Nework."
> 
> Also another thing I have noticed is Test SafetyNet fails with "Failed : Unable to resolve host [www.googleapis.com](http://www.googleapis.com)" so I guess its some sort of DNS resolution issue.
> 
> And no I don't think its due to LOS 20 since microG revived still works fine.

run `npem`.

**Comment by alou-S** [comment]
> run `npem`.
Sorry, I forgot to mention I flashed it via Magisk so thought it wasn't required to run. 

Anyway I ran it and it gives the following reply:
```
Failed to write while dumping service package: Broken pipe
package com.google.android.gms already is user app
package com.android.vending already is user app
package com.google.android.gms found
failed to grant permission android.permission.FAKE_PACKAGE_SIGNATURE
package com.android.vending found
failed to grant permission android.permission.FAKE_PACKAGE_SIGNATURE
package org.microg.nlp.backend.ichnaea already is user app
package org.microg.nlp.backend.apple already is user app
package com.google.android.gms found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.microg.nlp.backend.ichnaea found
already has permission android.permission.ACCESS_COARSE_LOCATION
package org.microg.nlp.backend.apple found
already has permission android.permission.ACCESS_COARSE_LOCATION
package com.google.android.gms found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.microg.nlp.backend.ichnaea found
already has permission android.permission.ACCESS_FINE_LOCATION
package org.microg.nlp.backend.apple found
already has permission android.permission.ACCESS_FINE_LOCATION
package com.google.android.gms found
permission android.permission.ACCESS_BACKGROUND_LOCATION granted
package com.google.android.gms found
permission android.permission.RECEIVE_SMS granted
package com.google.android.gms found
already has permission android.permission.GET_ACCOUNTS
package com.google.android.gms found
already has permission android.permission.READ_PHONE_STATE
package com.google.android.gms found
already has permission android.permission.READ_EXTERNAL_STORAGE
package com.google.android.gms found
already has permission android.permission.WRITE_EXTERNAL_STORAGE
```

**Comment by FriendlyNeighborhoodShane** [comment]
> Sorry, I forgot to mention I flashed it via Magisk so thought it wasn't required to run.

That's true, it should be run automatically in the case of magisk installations. But by "via magisk", do you mean as a magisk module from recovery, or from the Magisk Manager app? The latter is not a clean flash, since Android has already booted once, and could be why you're having this issue.

Are you using the Bromite webview? It's known to cause issues with microG.
Make sure no other device or router-level firewalls are getting in the way.

**Comment by alou-S** [comment]
> > Sorry, I forgot to mention I flashed it via Magisk so thought it wasn't required to run.
> 
> That's true, it should be run automatically in the case of magisk installations. But by "via magisk", do you mean as a magisk module from recovery, or from the Magisk Manager app? The latter is not a clean flash, since Android has already booted once, and could be why you're having this issue.
> 
> Are you using the Bromite webview? It's known to cause issues with microG. Make sure no other device or router-level firewalls are getting in the way.

I have flashed it from Magisk once it has completed first boot. 
No I am not using bromite webview and there are no device or router-level firewalls that I am aware of.

And finally like I told microG revived words perfectly every time.

**Comment by alou-S** [comment]
@FriendlyNeighborhoodShane Reopen since not fixed?

**Comment by crestcere** [comment]
@FriendlyNeighborhoodShane Just want to let you know, unfortunately same thing happens with twrp or magisk installation 🙁

**Comment by crestcere** [comment]
Have to enable network access both microg and play store then it works 😊
App-Info > Mobile Data and Wi-Fi > Allow network usage

**Comment by FriendlyNeighborhoodShane** [comment]
Right, sorry for the radio silence, everybody. I wasn't able to work on MinMicroG due to being busy with IRL stuff.

@crestcere nice find. I think that that this issue is related to LOS's feature to disable internet connection entirely, which does not exist on AOSP. This would seem to exclusively happen on LOS and other custom ROMs that inherit that feature.

For whatever reason they are disabling it by default for those apps.

**Comment by FriendlyNeighborhoodShane** [comment]
https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/d01d41bf8addc077ec468c3e5240586a7901c0e8 should fix it.

Also added a note to INSTALL.md about the issue.

Testing builds incoming.

**Comment by FriendlyNeighborhoodShane** [comment]
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.12.31

You can try these.

If you're using it MinMicroG in system mode you will have to run npem manually.

**Comment by alou-S** [comment]
Okay finally found enough time to wipe data and retest it. Seems like it is working just fine now.

Thanks for the fixes @FriendlyNeighborhoodShane
