### ISSUE TITLE
[UPDATE] Please !

### ISSUE THREAD

**Issue by Milor123** [FriendlyNeighborhoodShane/MinMicroG_releases#24]
Hey guys, I would that you updated this REPO, i want use it in A13 but i am not sure if the unestables builds works and this stable repo, only have 2 FEB updates. Thank you very much for your work, Actually is very useful for me. I am very happy !!!

**Comment by Milor123** [comment]
@FriendlyNeighborhoodShane  Bro...

**Comment by atamax** [comment]
@Milor123 You can try downloading the releases in the https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI repo, the latest as of now is 3 DEC 2022 there.

**Comment by NeoSDAP** [comment]
Working properly on CrDroid 9.4 (Android 13 QPR2) on a Poco X3 Pro

Perhaps, only microG and Mozilla UNLP Backend are a little bit outdated, but the installation worked fine.

**Comment by FriendlyNeighborhoodShane** [comment]
Sorry for taking a while. I made a release.
https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/releases/tag/2023.07.29
