### ISSUE TITLE
Google analytics???

### ISSUE THREAD

**Issue by sconim** [FriendlyNeighborhoodShane/MinMicroG_releases#25]
Why does microG incorporate Google analytics?

![microG trackers](https://user-images.githubusercontent.com/10010866/205369579-1b91abf0-90cc-4ae5-8933-69f6d6e464d1.jpg)

**Comment by FriendlyNeighborhoodShane** [comment]
This is not the repo for the microG app, just an installer.

And no, microG does not incorporate any of that. It just has dummy implementations of those APIs to not make apps crash.

**Comment by sconim** [comment]
I got it, thank you for clarifying!
