### ISSUE TITLE
KernelSU compatibility

### ISSUE THREAD

**Issue by asymcon** [FriendlyNeighborhoodShane/MinMicroG_releases#26]
Hi,
I'm trying to flash minimal zip from MinMicroG Installer v2.12.0 through KernelSU and get "Error: Specified file not found in archive". 
Went through the troubleshooting section, and couldn't figure out what's missing in the archive.
Any idea what's missing? Sadly my device doesn't come with mature recovery, so can't flash by any other means. 

Thanks,
A.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi asymcon,

KernelSU support was added after the last stable release was made. You can find a CI build with those changes here:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2023.07.31

**Comment by asymcon** [comment]
Got it, as usual, forgot to check the nightly repo. Thanks!
