### ISSUE TITLE
No license check with Play Store Addon on /e/OS (comes with microG already)

### ISSUE THREAD

**Issue by bege10** [FriendlyNeighborhoodShane/MinMicroG_releases#28]
I tried to get the real Play Store on a phone with /e/OS that comes with microG already. So I only installed the MinMicroG Play Store module with Magisk. Before I removed the FakeStore.
The Play Store is there after reboot but it does not

- show installed apps
- show apps for update
- allow apps to check for license (Tasker throws an error "no permission to check for license".

The problem not showing apps was solved after I additionally installed the Play Store as a user app. But license verification still does not work.
I saw that the Play Store permissions do not show signature spoofing while the FakeStore did.

What is necessary to get the Play Store running on an OS that comes with microG already?

**Comment by FriendlyNeighborhoodShane** [comment]
Hi, sorry for the late reply.

If you still are looking for the answer: Looking at /e/ OS's source, it seems they implement signature spoofing as a regular user-toggleable permission in the settings UI for apps. So you need to find where that permission is (the search bar might help) and enable it for Play Store.

**Comment by bege10** [comment]
Thank you for your research and answer. The problem is that in /e/OS the mentioned permission is not available to the user. I know it from LineageOS for microG that one can toggle that permission.
Meanwhile I tried the Play Store from another Magisk module that works not for all but most apps. Seems to remain a tricky thing.

**Comment by FriendlyNeighborhoodShane** [comment]
Hmm, then I'm not sure what else could be done, sorry. You could try granting the permission with:
```
adb shell pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE
```
