### ISSUE TITLE
Installation Failed -- Could Not Find A Rom In /

### ISSUE THREAD

**Issue by mattdementous** [FriendlyNeighborhoodShane/MinMicroG_releases#3]
I tried flashing this through LineageOS's Recovery, since it seems to be the only one I can use on Android 10 with my Pixel 3. TWRP is not currently available for this device on Android 10.
My issue is, when attempting to flash, it fails with the message:
FATAL ERROR: Could not find a ROMM in /
Installation failed.
Error in /sideload/package.zip (status 1)

**Comment by FriendlyNeighborhoodShane** [comment]
It can't find where the system is mounted in Lineage recovery.

Can you run terminal commands through ADB shell in it? Check the results from this:

 `find / -name build.prop -maxdepth 3`

If there are no results, try increasing the maxdepth value.

**Comment by mattdementous** [comment]
I ran it at a depth of 3 and it failed to find anything. A depth of 4 resulted in this result: /mnt/system/system/build.prop

**Comment by FriendlyNeighborhoodShane** [comment]
Which variant are you using? I'll try to upload a test build soon.

**Comment by thomasbonsirven** [comment]
Hello,

Just for other people have the same error with Lineage (or other recovery) :

So, if you have "Could not find a Rom in /" error  and you want to install microg :
 
- in Recovery home, go to Advanced ( Lineage recovery, TWRP i dont know )
- Enable ADB ( necessary is you install via adb sideload, if you use twrp, it's ok)
- Mount system
- restart installation Microg .zip

Work for me !
Ciao

**Comment by FriendlyNeighborhoodShane** [comment]
@thomasbonsirven A contributor submitted a PR so that those steps whould not be necessary. Will release builds with that change soon, after we've tested it.

**Comment by FriendlyNeighborhoodShane** [comment]
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2022.12.31

Here's a testing release that should fix this, if you feel like giving it a try.
