### ISSUE TITLE
 kernel su does not install

### ISSUE THREAD

**Issue by Lotybr** [FriendlyNeighborhoodShane/MinMicroG_releases#30]
please bring a version for the kernel as I really wanted to not depend on magisk

**Comment by Lotybr** [comment]
I used the latest version but it still doesn't work

**Comment by FriendlyNeighborhoodShane** [comment]
Hi, sorry for the late reply.

KernelSU support was added recently and isn't in the old release in this repo. It's present in the CI builds however: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2023.10.29
