### ISSUE TITLE
The Playstore is not visible and the "False keeps stopping" popup. 

### ISSUE THREAD

**Issue by ThatAnnoyingVegan** [FriendlyNeighborhoodShane/MinMicroG_releases#33]
I flashed **MinMicroG-Standard-2.12.0-20230729205842** build through **Magisk-26.4,** after rebooting to the system I get this "False keeps stopping" popup and there is no Play Store visible in the app drawer.

I tried considerable times installing and rebooting but to no avail, also version **MinMicroG-Standard-2.11.1-20220202153527** gives bootloop. :/ I'll leave some screenshots and a Magisk log file so you can investigate. Thank you.

Device: Poco F1
OS: Android 13, Proton Plus 13.2-Stable | OFFICIAL Vanilla
Security patch: August 5, 2023
Magisk version: 26.4 Official Stable
Magisk Module: MinMicroG-Standard-2.12.0-20230729205842.zip

![Screenshot_20240207-102431_Magisk.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/01617539-6b82-436f-b8e3-f0adef068ffe)

![Screenshot_20240207-102148_microG_Services.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/59c90a13-608b-4f3a-8fec-b939327e5eac)

![Screenshot_20240207-101955_Magisk.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/c6a836ba-1b7d-4233-af9b-2dec5dcc0ab8)

![Screenshot_20240207-102045_Settings.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/88d01aae-ebe2-450c-b076-8d72bc17efa7)

![Screenshot_20240207-102138_microG_Services.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/65e67b2a-74db-4725-8f49-c6e50b62e012)

![Screenshot_20240207-101831_Magisk.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/e230e8ec-1df0-4cf4-97b8-afa84d2d2918)

![Screenshot_20240207-102436_Magisk.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/fda729a3-db0f-4d6c-860c-288de38448e3)

![Screenshot_20240207-102306_App_Manager.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/29cb55ab-c1f6-4480-87e9-0a607a3a54c7)

![Screenshot_20240207-102256_App_Manager.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/41aba607-70e3-45dd-905a-ae63e253a1ce)

![Screenshot_20240207-102109_Settings.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/8f3122b5-cda9-42b1-bcb9-db4de5eb9058)

![magisk_install_log_2024-02-07T10.18.35.txt](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/14189443/magisk_install_log_2024-02-07T10.18.35.txt)

**Comment by FriendlyNeighborhoodShane** [comment]
Hi @ThatAnnoyingVegan,

Try flashing the last CI build: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases
I recommend flashing the zip through recovery instead of the magisk manager. The installer script can do some cleanups that way that it can't on a running system, and if you have the data partition decrypted it will still install as a magisk module.

Also that looks like a rom that comes preloaded with gapps. Since you have microg working already, playstore probably won't pose much of a problem to get working, but there will always be headaches because the rom will keep trying to bring its own versions of gapps back in OTAs, etc. I would recommend a vanilla (that comes withoutt gapps preloaded) ROM instead.

**Comment by ThatAnnoyingVegan** [comment]
> Hi @ThatAnnoyingVegan,
> 
> Try flashing the last CI build: https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases
> I recommend flashing the zip through recovery instead of the magisk manager. The installer script can do some cleanups that way that it can't on a running system, and if you have the data partition decrypted it will still install as a magisk module.
> 
> Also that looks like a rom that comes preloaded with gapps. Since you have microg working already, playstore probably won't pose much of a problem to get working, but there will always be headaches because the rom will keep trying to bring its own versions of gapps back in OTAs, etc. I would recommend a vanilla (that comes withoutt gapps preloaded) ROM instead.

Just flashed the given CI build, but the issue persists. I would flash through recovery but how would I uninstall the installed zip? You know Magisk gives the flexibility of removing it. The ROM I'm using is vanilla ![Screenshot_20240208-085916_App_Manager.png](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/assets/155138818/47c50cb0-55a3-4915-b120-d87f2f780f41)

**Comment by FriendlyNeighborhoodShane** [comment]
> The ROM I'm using is vanilla

... it is? How come you have so many google apps installed as system then?

**Comment by ThatAnnoyingVegan** [comment]
> > The ROM I'm using is vanilla
> 
> ... it is? How come you have so many google apps installed as system then?
> 

Point! I have just three of them, though I noticed LOS also has Google Assistant built-in. BTW, after dirty flashing the CI build from recovery the Play Store is force closes upon connecting to the internet :/

**Comment by FriendlyNeighborhoodShane** [comment]
> > > The ROM I'm using is vanilla
> > 
> > 
> > ... it is? How come you have so many google apps installed as system then?
> 
> Point! I have just three of them, though I noticed LOS also has Google Assistant built-in.

That's a weird build configuration to have for a "vanilla" rom, onsidering the assistant apps are useless without play services, and should come bundled in a gapps package anyway.

> BTW, after dirty flashing the CI build from recovery the Play Store is force closing upon connecting to the internet :/

I guess at least it appeared.

Clear data and cache for it. Then launch an `adb shell` from your pc (or a root shell on-device) and run the command:
```
npem
```

If it still doesn't launch, try getting a logcat of the crash.

**Comment by ThatAnnoyingVegan** [comment]
After cleaning data it didn't force stop. Also, I was able to install it through Magisk and got the PS  working this time with the ```CI``` build.

**Comment by FriendlyNeighborhoodShane** [comment]
Great!
