### ISSUE TITLE
"Permission to access location in the background" not possible, after fresh installation on LineageOS 17.1

### ISSUE THREAD

**Issue by IeP4nieF** [FriendlyNeighborhoodShane/MinMicroG_releases#4]
Hi,

I installed MinMicroG with Magisk on a LineageOS 17.1 with Signature Spoofing enabled. But I can't get the permission to access location in the background. Clicking on it unter "Self-Check" greys the field shortly but nothing happend.

I got all other permissions.

Searching for a solution I found several tipps on reddit and so on. They all told to install another GmsCore.apk. But the problem still exists.

So I can't use the location modules. And I think this is a bug, because it is there direct after installation.

Thanks for the great work, but this has to be fixed, so one can use MicroG location backends.

**Comment by FriendlyNeighborhoodShane** [comment]
Hello!

Actually, this seems to be a bug in microG's manifest itself. See: https://github.com/microg/android_packages_apps_GmsCore/issues/1100

But yeah, most people have fixed it by just extracting the microG GMSCore apk from the zip and just installing it as a user update over the system app. And on some ROMs it doesn't happen at all.

**Comment by FriendlyNeighborhoodShane** [comment]
Have you been able to get it checked in the last release? The steps (discovered in the above issue later on) to try in case you haven't are given in the release notes

**Comment by IeP4nieF** [comment]
Sorry, can't check this anymore, because I switched to LineageOS for microG 17.1 (https://lineage.microg.org/), which was released meanwhile. The installation seems to be much easier.

**Comment by FriendlyNeighborhoodShane** [comment]
No problem.
