### ISSUE TITLE
minmicroG doesn't "survive" dirty flash updates

### ISSUE THREAD

**Issue by krig6assaultrifle** [FriendlyNeighborhoodShane/MinMicroG_releases#5]
Hi FriendlyNeighborhoodShane,
Everytime I dirtyflashed my ROM (ArrowOS), minmicroG always dissapear from the ROM and I think that was related to addon.d (Maybe?) because IIRC, GApps like FlameGapps have addon.d survival that allows it to survive every update/dirty flash without losing settings and apps. I would like similar system be implemented on minmicroG. I don't want to flash it with Magisk because I don't like rooting my phone and possibly opening a lot of attack surfaces. Otherwise, minmicroG is near perfect. Keep up the hard work!

Thank you for reading and hopefully responsing to my comment.

**Comment by FriendlyNeighborhoodShane** [comment]
Hello!

Yep, you're correct, the addon.d mechanism is responsible for that. Strangely, MinMicroG already uses it and it works on my device.

Can you get a recovery log of dirty flashing your ROM? That might help in pointing out the problem.

**Comment by krig6assaultrifle** [comment]
> 
> 
> Hello!
> 
> Yep, you're correct, the addon.d mechanism is responsible for that. Strangely, MinMicroG already uses it and it does work on my device.
> 
> Can you get a recovery log of dirty flashing your ROM? That might help in pointing out the problem.

Okay, but since my ROM have nightly build, I will get the recovery logs and screenshot tomorrow, since I need the next build of my ROM to get the logs. But I did get the previous logs : 
[recovery_20201123_053603.log[1].zip](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/5582350/recovery_20201123_053603.log.1.zip)
[recovery_20201123_053825.log[1].zip](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/5582354/recovery_20201123_053825.log.1.zip)

Btw, the first log is dirtyflashing logs, while the second one is minmicroG flashing logs.
I use OrangeFox recovery, is it possibly because some setting in the recovery?

Thank you for responsing to my comment.
Cheers!

**Comment by FriendlyNeighborhoodShane** [comment]
Thanks. I think I have an idea™ of what's going wrong here, some stuff needs to be fixed on the MinMicroG side. Will try work on it soon!

**Comment by krig6assaultrifle** [comment]
> Thanks. I think I have an idea™ of what's going wrong here, some stuff needs to be fixed on the MinMicroG side. Will try work on it soon!

Okay, thanks. Looking for the fix soon!

**Comment by FriendlyNeighborhoodShane** [comment]
@krig6assaultrifle Did some work, should hopefully fix this problem.

Here's the CI builds for it:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2020.11.24

**Comment by krig6assaultrifle** [comment]
> @krig6assaultrifle Did some work, should hopefully fix this problem.
> 
> Here's the CI builds with the fix:
> https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2020.11.24
> 
> Lemme know what happens with these.

Ok mate, I already flashed the new minmicroG .zip from your link, but I have to test it tomorrow because, well, my next ROM update probably will came tomorrow! Anyway, thanks, mate.

**Comment by krig6assaultrifle** [comment]
It worked!! Thanks for both responsing and fixing the problem.
