### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by pwn0r** [FriendlyNeighborhoodShane/MinMicroG_releases#6]
Hi again,

trying on A11 on my second phone. 

Setup configuration:

lineage-18.1-20210524-nightly-oneplus3-signed
Magisk 23.0
MinMicroG-NoGoolag-UPDATELY-20210515002736.zip

The problem is that on Android11 location permissions are different. They changed so that always-on (background) can be enabled only by user in the settings. 

however the problem here is that I cannot do this for either Microg app or for any of the default location providers. So can only setup them as "while using the app" which does not work really unless you go into such app configuration. 

screenshots for illustration

<a href="https://imgbox.com/b7N9dsrO" target="_blank"><img src="https://thumbs2.imgbox.com/fd/03/b7N9dsrO_t.png" alt="image host"/></a>

<a href="https://imgbox.com/2v2G3KsQ" target="_blank"><img src="https://thumbs2.imgbox.com/35/e5/2v2G3KsQ_t.png" alt="image host"/></a>

Regarding SMS permission -- it is impossible to set it up for whatever reason. Even if going to settings manually. Could be Android11/LineageOS 18.1 bug? 

Is this permission really needed though?

**Comment by pwn0r** [comment]
Also, worth noting that _some apps_ actually have this permission in settings. I.e. it is possible to setup always-on background location permission. Just as an example -- DAVX app can get those background permissions on the same installation. 

Also documentation references regarding this change on android11:

https://developer.android.com/about/versions/11/privacy/location

https://developer.android.com/training/location/permissions#request-background-location

**Comment by FriendlyNeighborhoodShane** [comment]
Did you follow the steps here?
https://github.com/FriendlyNeighborhoodShane/MinMicroG/blob/master/install.md#permission-troubles-with-microg-and-gang

Step 1 (installing MicroG APK as user app update) seems to fix this for most.

Setialpha did a lot of digging into the issue here: https://github.com/microg/GmsCore/issues/1100

**Comment by FriendlyNeighborhoodShane** [comment]
RE: your second question, which I missed back in the morning, the SMS permission is needed for the automatic Firebase registration thing some apps use. You won't need it if you don't use those apps.

**Comment by pwn0r** [comment]
OK, was able to fix it with a workaround. Really incovenient though -- in order to work as before (i.e. on Android10) I had to install a user apps both microg core app and all the location providers (except nominatim of course).

**Comment by FriendlyNeighborhoodShane** [comment]
That's not a workaround, that's the only solution Android has left us :P

However, it was supposed to be done automatically by an init script on boot, which it is apparently not doing here. Since you have Magisk installed, I'm assuming MinMicroG is installed as a Magisk module?

Do you see the following lines in your Magisk manager logs (ladybug icon in the bottom bar)?
```
** late_start service mode running
* Running service.d scripts
* Running module service scripts
MinMicroG: exec [service.sh]
```

Also, you do not need to do this for backends, they do not actually need the ACCESS_BACKGROUND_LOCATION permission. Just granting it to MicroG should get you working NLP.

**Comment by pwn0r** [comment]
>However, it was supposed to be done automatically by an init script on boot, without needing user intervention, which it is >apparently not doing here. Since you have Magisk installed, I'm assuming MinMicroG is installed as a Magisk module?
> 
> Do you see the following lines in your Magisk manager logs (ladybug icon in the bottom bar)?
> 
> ```
> ** late_start service mode running
> * Running service.d scripts
> * Running module service scripts
> MinMicroG: exec [service.sh]
> ```

am I supposed to see these lines every reboot or just after installing microg? As I did not see them previously, just rebooted to twrp, reinstalled minmicrog zip and after reboot I can see these lines. 


> 
> Also, you do not need to do this for backends, they do not actually need the ACCESS_BACKGROUND_LOCATION permission. >Just granting it to MicroG should get you working NLP.

Interesting. I did it though for every location provider to replicated the same setup I had on LOS 17.1

**Comment by FriendlyNeighborhoodShane** [comment]
> am I supposed to see these lines every reboot or just after installing microg? As I did not see them previously, just rebooted to twrp, reinstalled minmicrog zip and after reboot I can see these lines.

You _should_ be seeing them every boot, even though it only needs to run once to do its job of installing the user app.

Did you confirm if it was even installed as a magisk module the first time around and you didn't accidentally just have it installed to system? That might explain why you weren't seeing its service.

**Comment by FriendlyNeighborhoodShane** [comment]
Closed because of inactivity. Just ping if you want it reopened
