### ISSUE TITLE
Minmicrog standard

### ISSUE THREAD

**Issue by fadhilm293** [FriendlyNeighborhoodShane/MinMicroG_releases#7]
can you modify the playstore so that there is no automatic update of google play services & playstore?

if possible please put in minmicrog standard version in next update.

Sorry for bad english.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi!

I don't patch the playstore myself, I just get the latest version patched by Nanolx from the NanoDroid F-Droid repository.

You can find the patches repository here: https://gitlab.com/Nanolx/microg-phonesky-iap-support

They do a few things to try to block automatic updates, but it seems that's not enough on newer play store versions. I don't have much ideas for what more can be done about it.
