### ISSUE TITLE
Microg, Aurora Droid and Aurora Store not working after OS update (NoGoolag Edition)

### ISSUE THREAD

**Issue by luissagasta** [FriendlyNeighborhoodShane/MinMicroG_releases#8]
Hi FriendlyNeighborhoodShane.

2 weeks ago I did a CrDroid (LineageOS based) clean install on my Mi 9T Pro.
I did the following steps:

1. Boot from TWRP
2. Wipe all necessary partitions
3. Flash crDroid last version (crDroidAndroid-11.0-20210624-raphael-v7.7)
4. Flash MinMicroG NoGoolag Edition (MinMicroG-NoGoolag-2.10-20210428084817-signed.zip)
5. Flash NikGApps (Google TTS)
6. Reboot

I installed MinMicroG without Magisk (I prefer not to installo Magisk).

Once I booted to the OS, I update MicroG to the last version using Aurora Droid.
Everything was working perfectly on my phone.

A few days ago I installed a crDroid OTA update.
During the install process, the TWRP did a backup of the NIkGApps (Google TTS) but I realiced that it dindn't backup MinMicrog apps.
After rebooting the phone, MicroG, Aurora Store and Aurora Droid stopped working.

**MicroG** Self-Check:
- Some permissions have dissapeared
- Play Store (Phonesky) is unchecked
- Some apps like Signal have an error indicating that the app was unable to register with Google Play Services

**Aurora Store**:
- When installing or updating an app the error "Install Failed. Install Aurora services" is shown. I checked the installed apps and Aurora Services has dissapeared.

**Aurora Droid**:
- When I try to install an app, the state gets stucked in "Installing".

I think, that the problem is that the MinMicroG installation is not persistent.
I checked an issue that could be related, but I see it is fixed and closed.
https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/issues/5

Please, could you help me?
Thank you in advance.
Regards.

**Comment by FriendlyNeighborhoodShane** [comment]
Hi!

Yes, at first look it does seem like MinMicroG is no longer installed in the system. MinMicroG does have an addon.d script (presumably just like nikgapps does), but it seems it did not work here for some reason.

Having the recovery logs from that OTA would be very useful, as they contain the debugging output of those addon.d scripts. But I don't think they are saved anywhere permanently. (If you have not booted into your recovery even once since the OTA they might be saved into `/cache/recovery/last_log`, but otherwise you're out of luck).

Some other details that might be useful:
 - What files are inside your `/system/addon.d` folder?
 - There are two checkboxes about Phonesky in MicroG's self-check, one about it being installed and another about it having the correct signature. Which one of those are unchecked for you?

If you have the time, try reinstalling MinMicroG and then dirty flashing your full ROM over that. You can then get the recovery logs from there and see if it's able to survive that. (A full flash is pretty different from an OTA but it might give us an idea of what's going wrong).

**Comment by luissagasta** [comment]
Hi FriendlyNeighborhoodShane.


> Having the recovery logs from that OTA would be very useful, as they contain the debugging output of those addon.d scripts. But I don't think they are saved anywhere permanently. (If you have not booted into your recovery even once since the OTA they might be saved into `/cache/recovery/last_log`, but otherwise you're out of luck).

Acces is denied to /cache/
My phone is not rooted. The only way I know to access that folder is using TWRP but as you mentioned before I shouldn't boot to TWRP to avoid the deletion of that file. Do you know how can I access that folder without booting TWRP?



> * What files are inside your `/system/addon.d` folder?
![addon_files](https://user-images.githubusercontent.com/14277186/126449417-345c396f-307e-4348-a03d-edff475c96c7.png)
The files in `/system/addon.d` folder are:
10-MinMicroG.sh
50-AndroidAuto.sh
50-GoogleContactsSyncAdapter.sh 
50-GoogleTTS.sh
50-lineage.sh

The 3 Google files were installed with Nikgapps.
I don't know what does the prefix number mean but MinMicrog is different to the other ones (it is 10 and the others are 50).



> * There are two checkboxes about Phonesky in MicroG's self-check, one about it being installed and another about it having the correct signature. Which one of those are unchecked for you?

The unchecked checkbox is the one about it being installed.



> If you have the time, try reinstalling MinMicroG and then dirty flashing your full ROM over that. You can then get the recovery logs from there and see if it's able to survive that. (A full flash is pretty different from an OTA but it might give us an idea of what's going wrong).

I don't understand you. Can you confirm that this are the steps to do?
1. - Boot from TWRP
2. - Flash MinMicrG NoGoolag Edition las version (the same version that is already installed)
3. - Flash crDroid last version (the same version that is already installed)
4.  - Get log from TWRP before rebooting

What happens with all my files, apks installed, data and configurations? Are they goig to be deleted?
As far as I know, my Android setup could be more unestable, with a dirty flashing.

Thank you!
Regards.

**Comment by FriendlyNeighborhoodShane** [comment]
> Acces is denied to /cache/
> My phone is not rooted. The only way I know to access that folder is using TWRP but as you mentioned before I shouldn't boot to TWRP to avoid the deletion of that file. Do you know how can I access that folder without booting TWRP?

I think recovery only overwrites the log when they 'exit' (but I'm not entirely sure). So if you have not gone into the recovery since then, you might still be able to get the OTA logs by booting into the recovery and copying `/cache/recovery/last_log` and `/cache/recovery/log` immediately.

> I don't know what does the prefix number mean but MinMicrog is different to the other ones (it is 10 and the others are 50).

The numbers don't really mean anything special. They're just used to choose the 'order' in which they are executed (since the recovery executes them in sorted order).

> I don't understand you. Can you confirm that this are the steps to do?
> 
>     1. * Boot from TWRP
> 
>     2. * Flash MinMicrG NoGoolag Edition las version (the same version that is already installed)
> 
>     3. * Flash crDroid last version (the same version that is already installed)
> 
>     4. * Get log from TWRP before rebooting

Yes.
 
> What happens with all my files, apks installed, data and configurations? Are they goig to be deleted?
> As far as I know, my Android setup could be more unestable, with a dirty flashing.

All of your data will still remain. Still, never hurts to keep a backup on hand always ;)

**Comment by luissagasta** [comment]
Finally, I did a new clean install to confirm the problem. After installing crDroid (Android 11), MinMicrog and Nikgapps, I updated crDroid using OTA update and everything installed by MinMigroG dissapeared.
TWRP automatically rebooted to System after installing, so I couldn't take the log.

After it, I did the dirty flash that you suggested and now I have the proper log file! I have attached it.
[recovery.log](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/6861139/recovery.log)

I hope the log file can help.
Thank you!

**Comment by FriendlyNeighborhoodShane** [comment]
Hmm interesting. I think I have an idea of the problem. I'll try to get to fixing it in a while, thinks!

**Comment by luissagasta** [comment]
I can test it when available.
Thank you for your effort.

**Comment by FriendlyNeighborhoodShane** [comment]
Try this build:
https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases/tag/2021.07.22

**Comment by luissagasta** [comment]
It worked! I haven't tested it deeply but it seems to work. After rebooting, everything is ok.

I don't know if it is relevant but I realiced that while instaling crDroid, it backed up the nikgapps apps and after installing it restored them (not with minmicrog apps).
[recovery.log](https://github.com/FriendlyNeighborhoodShane/MinMicroG_releases/files/6862030/recovery.log)

**Comment by FriendlyNeighborhoodShane** [comment]
You mean all those error messages about the nikgapps config file?

Yeah, those aren't from the MinMicroG addon.d. They're presumably from nikgapps' addon.d script, but they don't output a header message to make it clear.

**Comment by luissagasta** [comment]
I refer to the messages:

```
Backing up...
- Backing up AndroidAuto
- Backing up GoogleContactsSyncAdapter
- Backing up GoogleTTS
...[another installation messages]
Restoring...
- Restoring AndroidAuto
- Restoring GoogleContactsSyncAdapter
- Restoring GoogleTTS
```

You can find them in the recvery.log


Do you plan to release an oficial package?

**Comment by FriendlyNeighborhoodShane** [comment]
Probably not for a while.

**Comment by luissagasta** [comment]
Would you say that it is a "stable" release or would you recommend me to wait for next oficial release?

**Comment by FriendlyNeighborhoodShane** [comment]
You can use these. They're clean, I checked.

The reason that the CI builds come with so many warnings in the repo is that _usually_ I'm not the one making the builds, or know anything about them. The bot does it on a schedule, and I only get to see an email about it when I wake up.

**Comment by luissagasta** [comment]
ok, i will do a clean install with the package.
Thank you.
